version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filenest-api
    restart: always
    ports:
      - "9040:9040"
    volumes:
      - /www/FileNest:/app/upload
    environment:
      - GIN_MODE=release
    network_mode: bridge
