version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filenest-api
    restart: always
    ports:
      - "9040:9040"
    volumes:
      - /www/storage:/app/storage
    environment:
      - GIN_MODE=release
    networks:
      - filenest-network

networks:
  filenest-network:
    driver: bridge
