version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: filenest-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - filenest-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filenest-api
    restart: always
    ports:
      - "9040:9040"
    volumes:
      - ./storage:/app/storage
    environment:
      - GIN_MODE=release
    networks:
      - filenest-network

networks:
  filenest-network:
    driver: bridge
