/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ErrorHandler: typeof import('./src/components/common/ErrorHandler.vue')['default']
    FileContextMenu: typeof import('./src/components/file/FileContextMenu.vue')['default']
    FileIcon: typeof import('./src/components/file/FileIcon.vue')['default']
    FileList: typeof import('./src/components/home/FileList.vue')['default']
    FileOperationExample: typeof import('./src/components/FileOperationExample.vue')['default']
    FileStats: typeof import('./src/components/home/FileStats.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    HomeHeader: typeof import('./src/components/home/HomeHeader.vue')['default']
    LoadingState: typeof import('./src/components/common/LoadingState.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareDialog: typeof import('./src/components/file/ShareDialog.vue')['default']
    UploadConfig: typeof import('./src/components/UploadConfig.vue')['default']
    UploadDialog: typeof import('./src/components/file/UploadDialog.vue')['default']
    UploadProgress: typeof import('./src/components/file/UploadProgress.vue')['default']
  }
}
